<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var \Mdbhojwani\SaveForLater\Block\Link $block */
?>
<li class="link saveforlater" data-bind="scope: 'saveForLater'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= $block->escapeHtml($block->getLabel()) ?>
        <!-- ko if: saveForLater().counter -->
        <span data-bind="text: saveForLater().counter" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "saveForLater": {
                        "component": "Mdbhojwani_SaveForLater/js/view/saveforlater"
                    }
                }
            }
        }
    }

</script>
