<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Customer\Sidebar $block */
?>
<?php
$saveForLaterViewModel = $block->getData('saveForLaterDataViewModel');
?>
<?php if ($saveForLaterViewModel->isAllow()): ?>
    <div class="block block-saveforlater" data-bind="scope: 'saveForLater'">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></strong>
            <!-- ko if: saveForLater().counter -->
            <span data-bind="text: saveForLater().counter" class="counter"></span>
            <!-- /ko -->
        </div>
        <div class="block-content">
            <strong class="subtitle"><?= $block->escapeHtml(__('Last Added Items')) ?></strong>
            <!-- ko if: saveForLater().counter -->
                <ol class="product-items no-display"
                    id="saveforlater-sidebar"
                    data-bind="foreach: saveForLater().items, css: {'no-display': null}">
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="text: product_name"></span>
                                    </a>
                                </strong>
                                <div data-bind="html: product_price"></div>
                                <div class="product-item-actions">
                                    <!-- ko if: product_is_saleable_and_visible -->
                                    <div class="actions-primary">
                                        <!-- ko if: product_has_required_options -->
                                        <a href="#"
                                           data-bind="attr: {'data-post': add_to_cart_params}"
                                           class="action tocart primary">
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </a>
                                        <!-- /ko -->
                                        <!-- ko ifnot: product_has_required_options -->
                                            <button type="button"
                                                    class="action tocart primary"
                                                    data-bind="attr: {'data-post': add_to_cart_params}">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <!-- /ko -->
                                    </div>
                                    <!-- /ko -->
                                    <div class="actions-secondary">
                                        <a href="#"  data-bind="attr: {'data-post': delete_item_params}"
                                           title="<?= $block->escapeHtmlAttr(__('Remove This Item')) ?>"
                                           class="btn-remove action delete">
                                            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ol>
                <div class="actions-toolbar no-display" data-bind="css: {'no-display': null}">
                    <div class="primary">
                        <a class="action details"
                           href="<?= $block->escapeUrl($saveForLaterViewModel->getListUrl()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Go to Save For Later')) ?>">
                            <span><?= $block->escapeHtml(__('Go to Save For Later')) ?></span>
                        </a>
                    </div>
                </div>
            <!-- /ko -->
            <!-- ko ifnot: saveForLater().counter -->
                <div class="empty"><?= $block->escapeHtml(__('You have no items in the Save For Later.')) ?></div>
            <!-- /ko -->
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "saveForLater": {
                        "component": "Mdbhojwani_SaveForLater/js/view/saveforlater"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
