<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Cart\Item\Renderer\Actions\SaveForLater $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()) : ?>
    <a href="#"
       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
       class="use-ajax action tosaveforlater action-tosaveforlater">
        <span><?= $block->escapeHtml(__('Save for Later')) ?></span>
    </a>
<?php endif ?>
