<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var \Mdbhojwani\SaveForLater\Block\Share\Email\Items $block */
?>
<?php $l = $block->getSaveForLaterItemsCount() ?>
<div>
    <table>
        <tr>
            <?php $i = 0;
            foreach ($block->getSaveForLaterItems() as $item): $i++ ?>
                <?php /* @var \Mdbhojwani\SaveForLater\Model\Item $item */ ?>
                <?php /* @var \Magento\Catalog\Model\Product $_product */ ?>
                <?php $_product = $item->getProduct(); ?>
                <td class="col product">
                    <p>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                            <?php $productThumbnail = $block->getProductForThumbnail($item) ?>
                            <?= /* @noEscape */ $block->getImage($productThumbnail, 'product_small_image')->toHtml() ?>
                        </a>
                    </p>

                    <p>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                            <strong><?= $block->escapeHtml($_product->getName()) ?></strong>
                        </a>
                    </p>
                    <?php if ($block->hasDescription($item)): ?>
                        <p>
                            <strong><?= $block->escapeHtml(__('Comment')) ?>:</strong>
                            <br/><?= /* @noEscape */  $block->getEscapedDescription($item) ?>
                        </p>
                    <?php endif; ?>
                    <p>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                            <?= $block->escapeHtml(__('View Product')) ?>
                        </a>
                    </p>
                </td>
                <?php if ($i % 3 != 0): ?>
                    <td></td>
                <?php else: ?>
            </tr>
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
                    <?php if ($i < $l): ?>
                    <tr>
                    <?php endif ?>
                <?php endif ?>
            <?php endforeach ?>
    </table>
</div>
