<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var \Mdbhojwani\SaveForLater\Block\Rss\EmailLink $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var \Mdbhojwani\SaveForLater\Helper\Data $saveForLaterHelper */
$saveForLaterHelper = $block->getData('saveForLaterHelper');
?>
<?php if ($block->getLink()): ?>
<p id="saveforlater-rss-email-link">
    <?= $block->escapeHtml(__("RSS link to %1's save for later", $saveForLaterHelper->getCustomerName())) ?>
    <br />
    <a href="<?= $block->escapeUrl($block->getLink()) ?>"><?= $block->escapeUrl($block->getLink()) ?></a>
</p>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "font-size:12px; line-height:16px; margin:0 0 16px;",
        'p#saveforlater-rss-email-link'
    ) ?>
<?php endif; ?>
