<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Rss\Link $block */
?>
<?php if ($block->isRssAllowed() && $block->getLink() && $this->helper(\Mdbhojwani\SaveForLater\Helper\Data::class)->getSaveForLater()->getItemsCount()) : ?>
    <a href="<?= $block->escapeUrl($block->getLink()) ?>" class="action rss saveforlater">
        <span><?= $block->escapeHtml(__('RSS Feed')) ?></span>
    </a>
<?php endif; ?>
