<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Customer\SaveForLater\Item\Column\Actions $block */
?>
<?php $children = $block->getChildNames(); ?>
<?php if ($children) : ?>
    <div class="<?= $block->escapeHtmlAttr($block->getCssClass()) ?>">
        <?php foreach ($children as $childName) : ?>
            <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
        <?php endforeach;?>
    </div>
<?php endif; ?>
