<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var \Mdbhojwani\SaveForLater\Block\Customer\SaveForLater\Item\Column\Comment $block  */

/* @var \Mdbhojwani\SaveForLater\Model\Item $item */
$item = $block->getItem();
?>

<div class="field comment-box">
    <label class="label" for="product-item-comment-<?= $block->escapeHtmlAttr($item->getSaveforlaterItemId()) ?>">
        <span><?= $block->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="control">
        <textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getSaveforlaterItemId()) ?>" placeholder="<?= /* @noEscape */ $this->helper(\Mdbhojwani\SaveForLater\Helper\Data::class)->defaultCommentString() ?>" name="description[<?= $block->escapeHtmlAttr($item->getSaveforlaterItemId()) ?>]" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="product-item-comment" <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>><?= ($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
