<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Customer\SaveForLater\Item\Column\Edit $block */

/** @var \Mdbhojwani\SaveForLater\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()) : ?>
    <a class="action edit" href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>">
        <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
