<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Customer\SaveForLater\Item\Column\Image $block */

/** @var \Mdbhojwani\SaveForLater\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<a class="product-item-photo" tabindex="-1" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
    <?= $block->getImage($block->getProductForThumbnail($item), 'saveforlater_thumbnail')->toHtml() ?>
</a>
