<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Customer\SaveForLater\Button $block */
?>
<?php if ($block->getSaveForLater()->getItemsCount() && $block->getSaveForLater()->getShared() < $block->getConfig()->getSharingEmailLimit()) : ?>
    <button type="submit" name="save_and_share" title="<?= $block->escapeHtmlAttr(__('Share')) ?>" class="action share">
        <span><?= $block->escapeHtml(__('Share')) ?></span>
    </button>
<?php endif;?>
