<?php
/**
 * @category Mdbhojwani
 * @package Mdbhojwani_SaveForLater
 * @author Manish Bhojwani <manishbhojwani3@gmail.com>
 * @github https://github.com/mdbhojwani
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Mdbhojwani\SaveForLater\Block\Customer\SaveForLater\Button $block */
?>

<?php if ($block->getSaveForLater()->getItemsCount()) : ?>
    <button type="submit" name="do" title="<?= $block->escapeHtmlAttr(__('Update')) ?>" class="action update">
        <span><?= $block->escapeHtml(__('Update')) ?></span>
    </button>
<?php endif;?>
